name: fresh_graphql
description: An graphql link for token refresh. Built on top of package:graphql and manages authentication tokens transparently.
repository: https://github.com/felangel/fresh
issue_tracker: https://github.com/felangel/fresh/issues
homepage: https://github.com/felangel/fresh

version: 0.3.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  fresh: ^0.3.0
  graphql: ^4.0.0-beta.3
  http: ^0.12.1
  meta: ^1.1.8
  pedantic: ^1.9.0

dev_dependencies:
  mockito: ^4.1.1
  test: ^1.14.3
  test_coverage: ^0.4.1
